# Generated by Django 3.2.5 on 2022-11-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerKeyword',
            fields=[
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='final.keywordquestion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.team')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='final.choice')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='final.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.team')),
            ],
        ),
    ]
