# Generated by Django 3.2.5 on 2022-11-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_auto_20221107_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerKeyword',
            new_name='KeywordAnswer',
        ),
        migrations.DeleteModel(
            name='AnswerChoice',
        ),
    ]
