# Generated by Django 3.2.5 on 2022-11-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
