# Generated by Django 3.2.5 on 2022-11-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_keywordanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordanswer',
            name='sec',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
