# Generated by Django 3.2.5 on 2022-11-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_auto_20221118_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
        migrations.AddField(
            model_name='team',
            name='point_third',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='sec',
            field=models.IntegerField(default=0),
        ),
    ]
