# Generated by Django 3.2.5 on 2023-09-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0009_auto_20221124_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopFirst',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('final.team',),
        ),
        migrations.CreateModel(
            name='TopSecond',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('final.team',),
        ),
        migrations.CreateModel(
            name='TopThird',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('final.team',),
        ),
    ]
