version: "3"
services:
  api:
    build:
     context: .
     dockerfile: Dockerfile
    command: >
      bash -c "pip install -r requirements.txt &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_READ_ENV_FILE=True
    volumes:
      - ".:/app"
    ports:
      - "9000:8000"
    depends_on:
      - "mysql8"

  mysql8:
    image: mysql:8.0
    env_file: 
      - .env
    ports:
      - "9306:3306"
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin
    env_file: 
      - .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 9080:80

  gitlab-runner:
    container_name: django_runner
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config:/etc/gitlab-runner
    restart: always
