version: "3"
services:
  api:
    container_name: travelquiz_api
    build:
     context: .
     dockerfile: Dockerfile
    command: >
      bash -c "pip install -r requirements.txt &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_READ_ENV_FILE=True
    volumes:
      - ".:/app"
    ports:
      - "9000:8000"
    depends_on:
      - "mysql8"
    restart: always

  mysql8:
    container_name: travelquiz_mysql
    image: mysql:8.0
    env_file: 
      - .env
    ports:
      - "9306:3306"
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf

  game_server:
    container_name: travelquiz_final
    build: ./express
    volumes:
      - ./express:/usr/src/
    environment:
      - API_HOST=http://localhost:9000
    ports:
      - "5000:5000"
    depends_on:
      - "mysql8"
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: pachinko_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql8
      - PMA_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 12080:80
    volumes:
      - /sessions
