# Generated by Django 3.2.5 on 2022-04-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
