# Generated by Django 3.2.5 on 2022-05-20 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_title', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(0, 'default'), (1, 'waiting'), (2, 'playing'), (3, 'finished')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('group_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'default'), (1, 'waiting'), (2, 'ready'), (3, 'ingame'), (4, 'finished')], default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
