# Generated by Django 3.2.5 on 2022-05-26 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_groupuser_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAnswer',
            fields=[
                ('group_answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.choice')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
