# Generated by Django 3.2.5 on 2022-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220617_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
