# Generated by Django 3.2.5 on 2022-06-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_resets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='submits',
        ),
    ]
