# Generated by Django 3.2.5 on 2022-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_answer_submits'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wiki_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
