# Generated by Django 3.2.5 on 2022-06-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220618_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('island_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('descript', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.week')),
            ],
        ),
    ]
