# Generated by Django 3.2.5 on 2022-07-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_island'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='rank_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('selected', models.BooleanField(default=False)),
                ('corrects', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.week')),
            ],
        ),
    ]
