# Generated by Django 3.2.5 on 2022-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220712_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='show_rank',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
    ]
