# Generated by Django 3.2.5 on 2023-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_allow_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
