# Generated by Django 3.2.5 on 2023-10-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20231016_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'male'), (0, 'female')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
