# Generated by Django 3.2.5 on 2023-11-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20231108_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'choice'), (1, 'text')], default=0),
        ),
    ]
