# Generated by Django 3.2.5 on 2023-11-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20231109_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
