# Generated by Django 3.2.5 on 2023-11-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20231111_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='predict',
            field=models.IntegerField(default=0),
        ),
    ]
