# Generated by Django 3.2.5 on 2023-11-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rank_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='delta',
            field=models.IntegerField(default=0),
        ),
    ]
