# Generated by Django 3.2.5 on 2023-11-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rank_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'nam'), (1, 'nữ')], null=True),
        ),
    ]
