# Generated by Django 3.2.5 on 2023-12-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='turn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
