# Generated by Django 3.2.5 on 2023-12-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_answer_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('char_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('user_count', models.IntegerField(default=0)),
                ('anwser_count', models.IntegerField(default=0)),
                ('anwser_correct', models.IntegerField(default=0)),
            ],
        ),
    ]
