# Generated by Django 3.2.5 on 2023-12-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_chart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answer_at'], name='app_answer_answer__ed30c3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['prefecture'], name='app_user_prefect_11fd15_idx'),
        ),
    ]
