# Generated by Django 3.2.5 on 2023-12-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_answer_is_correct'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='app_answer_answer__ed30c3_idx',
        ),
        migrations.AddField(
            model_name='week',
            name='rank_status',
            field=models.SmallIntegerField(choices=[(0, 'Đã xong'), (1, 'Đang đợi'), (2, 'Đang chạy')], default=0),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answer_at', 'turn'], name='app_answer_answer__a5ea5c_idx'),
        ),
    ]
