# Generated by Django 3.2.5 on 2023-12-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20231210_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='rank_process',
            field=models.IntegerField(default=0),
        ),
    ]
